# Change these first
owner: alexanderl19 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: receipts.alexanderliu.com
    url: https://receipts.alexanderliu.com/CGjE1JTKfPfqYjueoptkq
  - name: alexanderliu.com Landing
    url: https://alexanderliu.com
  - name: alexanderliu.com Post
    url: https://alexanderliu.com/post/anchoring-power-strips-at-duke-s-innovation-co-lab
  - name: GitHub Profile GIF
    url: https://alexanderliu.com/api/internal/github-profile/gif
  - name: Code Block Embed
    url: https://code-block-embed.alexanderliu.dev/embed?lines=0,1,11:2,3,4,5,6,7,8,9,10&code=https://raw.githubusercontent.com/alexanderl19/code-block-embed/main/src/app.html
  - name: Assets
    url: https://assets.alexanderliu.com/assets

status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.alexanderliu.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/alexanderl19/status/master/icon.svg
  favicon: https://raw.githubusercontent.com/alexanderl19/status/master/icon.png
  faviconSvg: https://raw.githubusercontent.com/alexanderl19/status/master/icon.svg
  name: Status ‒ Alexander Liu
  introTitle: "**Status**"
  introMessage: Live statuses and uptime monitoring for many of my projects.
  navbar:
    - title: Home
      href: https://alexanderliu.com/
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/alexanderl19/status
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  responseTime: "0 1,5,9,13,17,21 * * *"
  uptime: "0 0 1 1 0"
